// <auto-generated />
using System;
using LogTunnel.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogTunnel.Infrastructure.Migrations
{
    [DbContext(typeof(LogTunnelDbContext))]
    [Migration("20260408163051_AddTranslationRenderingStatus")]
    partial class AddTranslationRenderingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.CodeRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("main")
                        .HasColumnName("default_branch");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_url");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("webhook_secret");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RemoteUrl")
                        .IsUnique();

                    b.ToTable("repositories", null, t =>
                        {
                            t.HasCheckConstraint("ck_repositories_host", "host IN ('github', 'gitlab', 'azure_devops')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_email");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("AuthoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authored_at");

                    b.Property<string[]>("ChangedFiles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("changed_files")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string[]>("ParentShas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("parent_shas")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedFiles")
                        .HasDatabaseName("commits_changed_files_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ChangedFiles"), "gin");

                    b.HasIndex("AuthorUserId", "AuthoredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("commits_author_authored_idx")
                        .HasFilter("author_user_id IS NOT NULL");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.HasIndex("TenantId", "AuthoredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("commits_tenant_authored_idx");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.CommitProject", b =>
                {
                    b.Property<Guid>("CommitId")
                        .HasColumnType("uuid")
                        .HasColumnName("commit_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("CommitId", "ProjectId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("commit_projects_project_idx");

                    b.ToTable("commit_projects", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockerNote")
                        .HasColumnType("text")
                        .HasColumnName("blocker_note");

                    b.Property<string>("BlockerStatus")
                        .HasColumnType("text")
                        .HasColumnName("blocker_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_at");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<Guid[]>("ProjectTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("project_tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("RawNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTags")
                        .HasDatabaseName("daily_logs_project_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProjectTags"), "gin");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "LogDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("daily_logs_blockers_idx")
                        .HasFilter("blocker_status IS NOT NULL");

                    b.HasIndex("TenantId", "UserId", "LogDate")
                        .IsUnique();

                    b.ToTable("daily_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_logs_blocker_status", "blocker_status IS NULL OR blocker_status IN ('need_help','waiting','unclear')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.DailyLogRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockerNote")
                        .HasColumnType("text")
                        .HasColumnName("blocker_note");

                    b.Property<string>("BlockerStatus")
                        .HasColumnType("text")
                        .HasColumnName("blocker_status");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("daily_log_id");

                    b.Property<string>("EditReason")
                        .HasColumnType("text")
                        .HasColumnName("edit_reason");

                    b.Property<DateTimeOffset>("EditedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<Guid[]>("ProjectTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("project_tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("RawNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_note");

                    b.HasKey("Id");

                    b.HasIndex("EditedBy");

                    b.HasIndex("DailyLogId", "EditedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("daily_log_revisions_log_idx");

                    b.ToTable("daily_log_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_log_revisions_blocker_status", "blocker_status IS NULL OR blocker_status IN ('need_help','waiting','unclear')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DashboardRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dashboard_role");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedUserId");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("invitations_tenant_email_idx");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_dashboard_role", "dashboard_role IN ('developer','team_lead','manager','ceo','marketing','admin')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("project_members_user_idx");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.PublicTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EditedContent")
                        .HasColumnType("text")
                        .HasColumnName("edited_content");

                    b.Property<string>("PublicSlug")
                        .HasColumnType("text")
                        .HasColumnName("public_slug");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TranslationId")
                        .HasColumnType("uuid")
                        .HasColumnName("translation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("TranslationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("public_translations_slug_idx")
                        .HasFilter("public_slug IS NOT NULL");

                    b.HasIndex("TenantId", "WorkflowStatus")
                        .HasDatabaseName("public_translations_status_idx");

                    b.ToTable("public_translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_public_translations_workflow_status", "workflow_status IN ('draft','approved','published')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.PublicTranslationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PublicTranslationId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_translation_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("PublicTranslationId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("public_translation_events_pt_idx");

                    b.ToTable("public_translation_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_public_translation_events_event_type", "event_type IN ('edited','approved','rejected','published','unpublished')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("refresh_tokens_user_expires_idx");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.RepositoryProjectMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PathFilter")
                        .HasColumnType("text")
                        .HasColumnName("path_filter");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RepositoryId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_repository_project_mappings_null_filter")
                        .HasFilter("path_filter IS NULL");

                    b.HasIndex("RepositoryId", "ProjectId", "PathFilter")
                        .IsUnique()
                        .HasDatabaseName("ux_repository_project_mappings_filtered")
                        .HasFilter("path_filter IS NOT NULL");

                    b.ToTable("repository_project_mappings", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.StandupExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("ExportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("exported_by");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ExportedBy");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TenantId", "LogDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("standup_exports_tenant_date_idx");

                    b.ToTable("standup_exports", null, t =>
                        {
                            t.HasCheckConstraint("ck_standup_exports_channel", "channel IN ('slack','teams','copy','email')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("team_members_user_idx");

                    b.ToTable("team_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_team_members_role", "role IN ('member','lead')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("company_context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("LlmApiKeyEnc")
                        .HasColumnType("bytea")
                        .HasColumnName("llm_api_key_enc");

                    b.Property<string>("LlmBaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("llm_base_url");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("llm_model");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("llm_provider");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_llm_provider", "llm_provider IN ('Anthropic','OpenAI','Ollama')");

                            t.HasCheckConstraint("ck_tenants_status", "status IN ('active','suspended')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by");

                    b.Property<string>("InputsHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inputs_hash");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ready")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("TenantId", "GeneratedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("translations_tenant_generated_idx");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("translations_pending_idx")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("TenantId", "ScopeKind", "ScopeId", "DateFrom", "DateTo", "Audience")
                        .IsUnique();

                    b.ToTable("translations", null, t =>
                        {
                            t.HasCheckConstraint("ck_translations_audience", "audience IN ('TechLead','Manager','CEO','Public')");

                            t.HasCheckConstraint("ck_translations_scope_kind", "scope_kind IN ('user','team','project','tenant')");

                            t.HasCheckConstraint("ck_translations_status", "status IN ('pending','rendering','ready','failed')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DashboardRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dashboard_role");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GitEmail")
                        .HasColumnType("text")
                        .HasColumnName("git_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "GitEmail")
                        .HasDatabaseName("users_git_email_idx");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_dashboard_role", "dashboard_role IN ('developer','team_lead','manager','ceo','marketing','admin')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active','disabled')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean")
                        .HasColumnName("signature_valid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("RepositoryId", "DeliveryId")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("webhook_deliveries_repo_received_idx");

                    b.ToTable("webhook_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_webhook_deliveries_outcome", "outcome IS NULL OR outcome IN ('ok','duplicate','invalid_signature','error')");
                        });
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.CodeRepository", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Commit", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.CommitProject", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Commit", null)
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.DailyLog", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.DailyLogRevision", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.DailyLog", null)
                        .WithMany()
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("EditedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.PublicTranslation", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Translation", null)
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.PublicTranslationEvent", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.PublicTranslation", null)
                        .WithMany()
                        .HasForeignKey("PublicTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.RepositoryProjectMapping", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.StandupExport", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ExportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Team", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.Translation", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTunnel.Core.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("LogTunnel.Core.Domain.Entities.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogTunnel.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
